apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-dyvg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-dyvg
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-dyvg
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-dyvg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-dyvg
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nvkf-tenant/rhtap-demo-app/hacbs-test-project-dyvg@sha256:d6b9ac1dbf7c2ea58dae324f9a02e9c9e416511d8ba8fd558e9f6c6c71969d97
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
